name = "acnos-voip-relay"
main = "src/worker.js"
compatibility_date = "2026-07-06"

[vars]
GATEWAY_KEYWORD = "neopix-super-secret-2026"

[[d1_databases]]
binding = "DB"
database_name = "neopix_voip_db"
database_id = "your_cloudflare_d1_id_here"
